/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    customers: CustomerAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    ingredients: Ingredient;
    domains: Domain;
    rhythms: Rhythm;
    blocks: Block;
    sources: Source;
    products: Product;
    formulations: Formulation;
    suppliers: Supplier;
    'product-submissions': ProductSubmission;
    lots: Lot;
    'stock-movements': StockMovement;
    orders: Order;
    'payment-events': PaymentEvent;
    customers: Customer;
    consents: Consent;
    'customer-products': CustomerProduct;
    plans: Plan;
    'plan-items': PlanItem;
    'intake-logs': IntakeLog;
    reviews: Review;
    'symptom-reports': SymptomReport;
    users: User;
    'audit-log': AuditLog;
    media: Media;
    'private-files': PrivateFile;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    ingredients: IngredientsSelect<false> | IngredientsSelect<true>;
    domains: DomainsSelect<false> | DomainsSelect<true>;
    rhythms: RhythmsSelect<false> | RhythmsSelect<true>;
    blocks: BlocksSelect<false> | BlocksSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    formulations: FormulationsSelect<false> | FormulationsSelect<true>;
    suppliers: SuppliersSelect<false> | SuppliersSelect<true>;
    'product-submissions': ProductSubmissionsSelect<false> | ProductSubmissionsSelect<true>;
    lots: LotsSelect<false> | LotsSelect<true>;
    'stock-movements': StockMovementsSelect<false> | StockMovementsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'payment-events': PaymentEventsSelect<false> | PaymentEventsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    consents: ConsentsSelect<false> | ConsentsSelect<true>;
    'customer-products': CustomerProductsSelect<false> | CustomerProductsSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    'plan-items': PlanItemsSelect<false> | PlanItemsSelect<true>;
    'intake-logs': IntakeLogsSelect<false> | IntakeLogsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'symptom-reports': SymptomReportsSelect<false> | SymptomReportsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'private-files': PrivateFilesSelect<false> | PrivateFilesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'de' | 'en') | ('es' | 'de' | 'en')[];
  globals: {
    'shop-settings': ShopSetting;
  };
  globalsSelect: {
    'shop-settings': ShopSettingsSelect<false> | ShopSettingsSelect<true>;
  };
  locale: 'es' | 'de' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Customer | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients".
 */
export interface Ingredient {
  id: number;
  name: string;
  /**
   * Minúsculas y guiones, p. ej. «rhodiola». No cambia entre idiomas.
   */
  slug: string;
  scientificName?: string | null;
  /**
   * Solo equipo editorial · búsqueda: sinónimos, nombres de etiqueta y de otros idiomas.
   */
  otherNames?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  category: 'vitamin' | 'mineral' | 'amino-acid' | 'fatty-acid' | 'plant-extract' | 'fungus' | 'other';
  /**
   * Solo para familias: omega-3 → EPA, DHA; complejo B → cada vitamina.
   */
  components?: (number | Ingredient)[] | null;
  /**
   * Lo ve el cliente · máx. 160 caracteres.
   */
  summary?: string | null;
  /**
   * Lo ve el cliente · máx. 300 caracteres.
   */
  whatIsShort?: string | null;
  primaryDomain?: (number | null) | Domain;
  /**
   * Solo con función distinta, observable y con respaldo humano.
   */
  secondaryDomain?: (number | null) | Domain;
  /**
   * Lo ve el personal de la droguería
   */
  domainJustification?: string | null;
  /**
   * Lo ve el personal de la droguería · máx. 400 caracteres.
   */
  mechanisms?: string | null;
  /**
   * Lo ve el personal de la droguería · nombre del campo provisional («Función de regreso MAT»).
   */
  goalTechnical?: string | null;
  /**
   * Lo ve el cliente · qué cambio concreto tendría sentido observar.
   */
  goalEveryday?: string | null;
  /**
   * Lo ve el cliente · una sola pregunta.
   */
  reviewQuestion?: string | null;
  /**
   * Lo ve el personal de la droguería
   */
  preferredForm?: string | null;
  labelMustDeclare?:
    | (
        | 'species'
        | 'part'
        | 'extract-type'
        | 'der'
        | 'solvent'
        | 'standardization'
        | 'chemical-form'
        | 'elemental-amount'
        | 'amount-per-dose'
        | 'manufacturer'
      )[]
    | null;
  usualStandardization?:
    | {
        marker: string;
        percent?: number | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  labelAvoid?: string | null;
  /**
   * Lo ve el personal de la droguería · información de contexto; no es un límite de seguridad (Libro 2, n.º 19).
   */
  referenceDose?: {
    amount?: number | null;
    unit?: ('mg' | 'ug' | 'g' | 'IU' | 'ml' | 'CFU') | null;
    basis?: ('extract' | 'elemental' | 'compound' | 'active' | 'blend') | null;
    frequency?: ('per-day' | 'per-use' | 'per-week') | null;
    /**
     * p. ej. «de extracto de raíz y rizoma»
     */
    refersTo?: string | null;
  };
  otherDoseReferences?:
    | {
        label: string;
        amount?: number | null;
        unit?: ('mg' | 'ug' | 'g' | 'IU' | 'ml' | 'CFU') | null;
        source?: (number | null) | Source;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  block?: (number | null) | Block;
  mealRelation?: ('fasting' | 'with-food' | 'any') | null;
  mealNote?: string | null;
  /**
   * Lo ve el cliente · se muestra junto a cada toma.
   */
  usageInstructions?: string | null;
  /**
   * p. ej. «activadora». Regla pendiente de confirmar (pendiente n.º 4).
   */
  introductionTags?: string[] | null;
  introductionNote?: string | null;
  rhythm?: (number | null) | Rhythm;
  /**
   * Dejar vacío para usar las de la plantilla. Si se cambian, justificar.
   */
  rhythmOverride?: {
    useWeeks?: number | null;
    pauseWeeks?: number | null;
    reviewEveryWeeks?: number | null;
    justification?: string | null;
  };
  selectiveUse?: boolean | null;
  selectiveCircumstances?: string | null;
  /**
   * Lo ve el cliente · 2–3 situaciones concretas. Se convierten en preguntas de la revisión.
   */
  observations?:
    | {
        text: string;
        answerType?: ('yes-no' | 'scale' | 'text') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Lo ve el personal de la droguería · orientan al profesional. El sistema no decide.
   */
  decisionCriteria?:
    | {
        situation: string;
        decision?: ('continue' | 'adjust' | 'new-cycle' | 'simplify' | 'pause' | 'withdraw' | 'refer') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Lo ve el cliente
   */
  tolerability?: string | null;
  /**
   * Lo ve el cliente · p. ej. «de frecuencia poco definida, generalmente leves y transitorios».
   */
  adverseEffectsSummary?: string | null;
  adverseEffects?:
    | {
        effect: string;
        frequency?: ('unknown' | 'rare' | 'uncommon' | 'common') | null;
        intensity?: ('mild' | 'moderate' | 'severe' | 'variable') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * «No» nunca se muestra como «sin riesgo». El detalle va en la lista correspondiente.
   */
  alertSummary: {
    status: 'yes' | 'no' | 'not-evaluated' | 'insufficient';
    text?: string | null;
  };
  precautions?:
    | {
        situation: string;
        severity?: ('low' | 'moderate' | 'high') | null;
        evidence?:
          | ('theoretical' | 'preclinical' | 'case-reports' | 'human-limited' | 'human-consistent' | 'established')
          | null;
        visibleToCustomer?: boolean | null;
        action?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * «No» nunca se muestra como «sin riesgo». El detalle va en la lista correspondiente.
   */
  interactionSummary: {
    status: 'yes' | 'no' | 'not-evaluated' | 'insufficient';
    text?: string | null;
  };
  interactions?:
    | {
        with: string;
        kind?: ('medication' | 'drug-class' | 'supplement' | 'food' | 'other') | null;
        severity?: ('low' | 'moderate' | 'high') | null;
        evidence?:
          | ('theoretical' | 'preclinical' | 'case-reports' | 'human-limited' | 'human-consistent' | 'established')
          | null;
        visibleToCustomer?: boolean | null;
        action?: string | null;
        id?: string | null;
      }[]
    | null;
  pauseSignals?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  urgentSignals?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lo ve el cliente en «Saber más»
   */
  evidenceSummary?: string | null;
  claims?:
    | {
        claim: string;
        classification: 'established' | 'possible' | 'exploratory' | 'traditional-use';
        population?: string | null;
        preparationAndDose?: string | null;
        result?: string | null;
        sources?: (number | Source)[] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Lo ve el cliente en «Saber más» · punto 2
   */
  moreWhatIs?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Lo ve el personal de la droguería · punto 3, sin el marco del aislamiento
   */
  moreWhyUseful?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Lo ve el personal de la droguería · punto 4
   */
  moreHowToUse?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * C+ y P · punto 5
   */
  moreCautions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sources?: (number | Source)[] | null;
  author?: (number | null) | User;
  reviewer?: (number | null) | User;
  approvedAt?: string | null;
  internalNotes?: string | null;
  /**
   * Solo las fichas aprobadas se publican. Aprobar requiere rol de revisión.
   */
  editorialStatus: 'draft' | 'in-review' | 'approved' | 'historical' | 'retired';
  /**
   * Solo los productos cuyos ingredientes funcionales están en el pool pueden venderse o añadirse a un plan (Libro 1 v2.0, cap. 2). Cambiarlo requiere rol de revisión.
   */
  poolStatus: 'in-pool' | 'candidate' | 'historical' | 'excluded';
  /**
   * Un idioma no aprobado no se muestra al cliente (Libro 2, n.º 36).
   */
  translationStatus?: ('not-started' | 'draft' | 'reviewed' | 'approved') | null;
  regulatoryStatusCH: 'pending' | 'checked' | 'not-suitable';
  regulatoryNote?: string | null;
  isFictional?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domains".
 */
export interface Domain {
  id: number;
  /**
   * DF-1 … DF-7. No cambia aunque cambien los nombres.
   */
  code: string;
  clientName: string;
  technicalName: string;
  description?: string | null;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  title: string;
  kind: 'study' | 'review' | 'monograph' | 'regulatory' | 'internal' | 'other';
  authors?: string | null;
  year?: number | null;
  publication?: string | null;
  url?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocks".
 */
export interface Block {
  id: number;
  code: string;
  name: string;
  description?: string | null;
  defaultTime: string;
  mealRelation?: ('fasting' | 'with-food' | 'any') | null;
  order: number;
  provisional?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rhythms".
 */
export interface Rhythm {
  id: number;
  code: string;
  name: string;
  description?: string | null;
  continuous?: boolean | null;
  useWeeks?: number | null;
  pauseWeeks?: number | null;
  reviewEveryWeeks?: number | null;
  /**
   * Cosecha: «al menos doce semanas de pausa».
   */
  pauseIsMinimum?: boolean | null;
  /**
   * Cultivo puede incluir uso ante circunstancias definidas.
   */
  allowsSelectiveUse?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'reviewer' | 'operations' | 'support';
  /**
   * Solo informativo. No concede permisos.
   */
  professionalTitle?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug?: string | null;
  brand?: string | null;
  manufacturer?: string | null;
  form: 'capsule' | 'softgel' | 'tablet' | 'powder' | 'liquid' | 'gummy' | 'other';
  /**
   * p. ej. «Kapsel», «capsule»
   */
  servingUnit: string;
  unitsPerContainer?: number | null;
  /**
   * Sin declaraciones de salud: describe el producto, no sus efectos.
   */
  shortDescription?: string | null;
  /**
   * Identificador, no prueba de composición.
   */
  gtin?: string[] | null;
  /**
   * Se rellena al verificar una formulación.
   */
  currentFormulation?: (number | null) | Formulation;
  labelImages?: (number | Media)[] | null;
  sku?: string | null;
  price?: number | null;
  /**
   * Confirmar con asesoría fiscal.
   */
  vatRate?: number | null;
  supplier?: (number | null) | Supplier;
  /**
   * Para calcular el peso del paquete.
   */
  weightGrams?: number | null;
  /**
   * Solo lo que podamos justificar. «Fabricado en Suiza» no convierte toda materia prima en suiza (Libro 1 v2.0, cap. 3).
   */
  origin?: {
    countryOfManufacture?: string | null;
    packagingPlace?: string | null;
    responsibleCompany?: string | null;
    ingredientOrigin?: string | null;
    evidence?: string | null;
  };
  storage?: {
    conditions?: string | null;
    /**
     * Si se marca, no puede venderse con envío estándar.
     */
    coldChainRequired?: boolean | null;
  };
  kind: 'catalog' | 'external';
  /**
   * Poner a la venta exige formulación verificada, pool, ficha aprobada, proveedor, precio y origen.
   */
  saleStatus: 'not-for-sale' | 'for-sale' | 'paused' | 'discontinued';
  isFictional?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formulations".
 */
export interface Formulation {
  id: number;
  product: number | Product;
  label?: string | null;
  version?: number | null;
  validFrom?: string | null;
  composition?:
    | {
        ingredient: number | Ingredient;
        /**
         * Vacío si la etiqueta no la declara.
         */
        amount?: number | null;
        unit?: ('mg' | 'ug' | 'g' | 'IU' | 'ml' | 'CFU') | null;
        basis: 'extract' | 'elemental' | 'compound' | 'active' | 'blend';
        /**
         * p. ej. «citrato de magnesio», «colecalciferol»
         */
        chemicalForm?: string | null;
        extractDetails?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Lo que dice el fabricante. Se muestra al cliente como referencia; nunca se convierte en una pauta personal (Libro 1 v2.0, cap. 4).
   */
  labelInfo?: {
    directions?: string | null;
    dailyUnitsMin?: number | null;
    dailyUnitsMax?: number | null;
    warnings?: string | null;
  };
  excipients?: string | null;
  allergens?: string | null;
  verificationStatus: 'pending' | 'verified' | 'rejected' | 'superseded';
  /**
   * Etiqueta, ficha del fabricante, archivo de la droguería…
   */
  source?: string | null;
  sourceDate?: string | null;
  verifiedBy?: (number | null) | User;
  verifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers".
 */
export interface Supplier {
  id: number;
  name: string;
  status: 'candidate' | 'confirmed' | 'inactive';
  country?: string | null;
  website?: string | null;
  contact?: {
    person?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  /**
   * Precio profesional, IVA, mínimos, transporte de entrada, plazos de pago, permisos de reventa y uso de imágenes.
   */
  terms?: {
    summary?: string | null;
    minimumOrder?: string | null;
    paymentTerms?: string | null;
    inboundShipping?: string | null;
    resaleRights?: string | null;
    documents?: (number | Media)[] | null;
  };
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-submissions".
 */
export interface ProductSubmission {
  id: number;
  customer: number | Customer;
  productName: string;
  manufacturer: string;
  declaredIngredients?:
    | {
        ingredient: number | Ingredient;
        amountText?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Si se rellena, el producto no se incorpora al plan: queda como solicitud de ampliación del catálogo.
   */
  otherIngredients?: string | null;
  photos?: (number | PrivateFile)[] | null;
  status: 'pending-verification' | 'verified' | 'rejected' | 'out-of-pool';
  /**
   * Producto (tipo «externo») con su composición verificada: producto, fabricante, molécula, forma, cantidad, composición, etiqueta y versión.
   */
  resultProduct?: (number | null) | Product;
  reviewNote?: string | null;
  verifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  alias: string;
  language: 'de' | 'en';
  adultConfirmed: boolean;
  timezone?: string | null;
  isFictional?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "private-files".
 */
export interface PrivateFile {
  id: number;
  owner?: (number | null) | Customer;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lots".
 */
export interface Lot {
  id: number;
  product: number | Product;
  lotNumber: string;
  expiryDate: string;
  /**
   * Por defecto, la vigente al recibirlo.
   */
  formulation?: (number | null) | Formulation;
  supplier?: (number | null) | Supplier;
  receivedOn?: string | null;
  /**
   * Solo al crear. Después, cualquier cambio de cantidad es un movimiento de stock.
   */
  quantityReceived?: number | null;
  supplierDocument?: string | null;
  storageLocation?: string | null;
  status: 'available' | 'held' | 'recalled';
  statusNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements".
 */
export interface StockMovement {
  id: number;
  lot: number | Lot;
  product: number | Product;
  kind: 'receipt' | 'shipment' | 'return' | 'release' | 'hold' | 'write-off' | 'adjustment';
  bucket: 'sellable' | 'held';
  quantity: number;
  order?: (number | null) | Order;
  reason: string;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  customer: number | Customer;
  email?: string | null;
  language?: ('de' | 'en') | null;
  /**
   * Producto, versión de composición y precio en el momento de la compra.
   */
  lines?:
    | {
        product: number | Product;
        formulation: number | Formulation;
        productName: string;
        quantity: number;
        unitPriceCents: number;
        vatRate?: number | null;
        lots?:
          | {
              lot: number | Lot;
              quantity: number;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  totals?: {
    subtotalCents?: number | null;
    shippingCents?: number | null;
    vatCents?: number | null;
    totalCents?: number | null;
  };
  shippingAddress: {
    name: string;
    street: string;
    addressLine2?: string | null;
    postalCode: string;
    city: string;
    country?: string | null;
  };
  shippingMethod?: {
    code?: string | null;
    label?: string | null;
    priceCents?: number | null;
  };
  payment?: {
    provider?: ('simulated' | 'stripe' | 'payrexx') | null;
    status?: ('pending' | 'succeeded' | 'failed') | null;
    reference?: string | null;
    paidAt?: string | null;
  };
  shipment?: {
    trackingNumber?: string | null;
    depositedOn?: string | null;
    weightGrams?: number | null;
    deliveredOn?: string | null;
  };
  /**
   * Las unidades devueltas entran como retenidas. Devolver no borra el historial de uso del cliente.
   */
  returns?:
    | {
        product: number | Product;
        lot: number | Lot;
        quantity: number;
        reason?: string | null;
        refundCents?: number | null;
        processed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  cancellationReason?: string | null;
  incidents?: string | null;
  status: 'pending-payment' | 'paid' | 'packed' | 'shipped' | 'delivered' | 'cancelled' | 'returned';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-events".
 */
export interface PaymentEvent {
  id: number;
  provider: 'simulated' | 'stripe' | 'payrexx';
  eventId: string;
  type: string;
  order: number | Order;
  amountCents: number;
  outcome?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consents".
 */
export interface Consent {
  id: number;
  customer: number | Customer;
  kind: 'terms' | 'privacy' | 'tracking-data';
  version: string;
  grantedAt?: string | null;
  revokedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-products".
 */
export interface CustomerProduct {
  id: number;
  customer: number | Customer;
  product: number | Product;
  /**
   * La del envase del cliente. No cambia sola si el fabricante cambia la fórmula.
   */
  formulation?: (number | null) | Formulation;
  status: 'suggested' | 'active' | 'archived';
  source?: ('purchase' | 'external' | 'added-by-customer') | null;
  order?: (number | null) | Order;
  submission?: (number | null) | ProductSubmission;
  confirmedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  customer: number | Customer;
  /**
   * Separada del plan del cliente. Solo cambia si un profesional revisa realmente el plan.
   */
  professionalReview: {
    status: 'not-reviewed' | 'requested' | 'reviewed';
    reviewer?: (number | null) | User;
    reviewedAt?: string | null;
    note?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plan-items".
 */
export interface PlanItem {
  id: number;
  customer: number | Customer;
  plan?: (number | null) | Plan;
  customerProduct: number | CustomerProduct;
  product?: (number | null) | Product;
  formulation?: (number | null) | Formulation;
  intakes?:
    | {
        block: number | Block;
        time?: string | null;
        servings: number;
        id?: string | null;
      }[]
    | null;
  note?: string | null;
  scheduleType: 'daily' | 'weekdays' | 'selective';
  weekdays?: ('mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun')[] | null;
  selectiveCircumstances?: string | null;
  /**
   * La elige el cliente. La compra o la entrega no la fijan.
   */
  startDate: string;
  rhythm?: (number | null) | Rhythm;
  reviewOn?: string | null;
  continuous?: boolean | null;
  useWeeks?: number | null;
  pauseWeeks?: number | null;
  reviewEveryWeeks?: number | null;
  pauseIsMinimum?: boolean | null;
  reviewQuestion?: string | null;
  observations?:
    | {
        text: string;
        answerType?: ('yes-no' | 'scale' | 'text') | null;
        id?: string | null;
      }[]
    | null;
  status: 'active' | 'paused' | 'interrupted' | 'ended';
  /**
   * Una pausa no alarga ni reinicia el ciclo.
   */
  pauses?:
    | {
        from: string;
        to?: string | null;
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  endedOn?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intake-logs".
 */
export interface IntakeLog {
  id: number;
  planItem: number | PlanItem;
  customer?: (number | null) | Customer;
  date: string;
  intakeIndex?: number | null;
  status: 'taken' | 'skipped' | 'postponed';
  servings?: number | null;
  note?: string | null;
  loggedAt?: string | null;
  correctedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  planItem: number | PlanItem;
  customer?: (number | null) | Customer;
  dueDate: string;
  kind: 'periodic' | 'end-of-use' | 'end-of-pause' | 'extra';
  status: 'pending' | 'answered' | 'closed';
  reviewQuestion?: string | null;
  answer?: {
    questionAnswer?: string | null;
    observations?:
      | {
          text?: string | null;
          answerType?: ('yes-no' | 'scale' | 'text') | null;
          value?: string | null;
          id?: string | null;
        }[]
      | null;
    tolerability?: ('good' | 'some' | 'poor') | null;
    adherence?: ('as-planned' | 'partial' | 'stopped') | null;
    perceivedChange?: string | null;
    answeredAt?: string | null;
  };
  outcome?: ('continue' | 'adjust' | 'new-cycle' | 'simplify' | 'pause' | 'withdraw' | 'refer') | null;
  closedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "symptom-reports".
 */
export interface SymptomReport {
  id: number;
  customer: number | Customer;
  planItem?: (number | null) | PlanItem;
  kind: 'question' | 'discomfort' | 'adherence' | 'stopped';
  severity?: ('mild' | 'moderate' | 'severe') | null;
  description: string;
  reportedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  targetCollection: string;
  targetId: string;
  operation: 'create' | 'update' | 'delete';
  changedFields?: string[] | null;
  reason?: string | null;
  actorCollection?: string | null;
  actorId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'ingredients';
        value: number | Ingredient;
      } | null)
    | ({
        relationTo: 'domains';
        value: number | Domain;
      } | null)
    | ({
        relationTo: 'rhythms';
        value: number | Rhythm;
      } | null)
    | ({
        relationTo: 'blocks';
        value: number | Block;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'formulations';
        value: number | Formulation;
      } | null)
    | ({
        relationTo: 'suppliers';
        value: number | Supplier;
      } | null)
    | ({
        relationTo: 'product-submissions';
        value: number | ProductSubmission;
      } | null)
    | ({
        relationTo: 'lots';
        value: number | Lot;
      } | null)
    | ({
        relationTo: 'stock-movements';
        value: number | StockMovement;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'payment-events';
        value: number | PaymentEvent;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'consents';
        value: number | Consent;
      } | null)
    | ({
        relationTo: 'customer-products';
        value: number | CustomerProduct;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'plan-items';
        value: number | PlanItem;
      } | null)
    | ({
        relationTo: 'intake-logs';
        value: number | IntakeLog;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'symptom-reports';
        value: number | SymptomReport;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'private-files';
        value: number | PrivateFile;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'customers';
        value: number | Customer;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'customers';
        value: number | Customer;
      }
    | {
        relationTo: 'users';
        value: number | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients_select".
 */
export interface IngredientsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  scientificName?: T;
  otherNames?:
    | T
    | {
        value?: T;
        id?: T;
      };
  category?: T;
  components?: T;
  summary?: T;
  whatIsShort?: T;
  primaryDomain?: T;
  secondaryDomain?: T;
  domainJustification?: T;
  mechanisms?: T;
  goalTechnical?: T;
  goalEveryday?: T;
  reviewQuestion?: T;
  preferredForm?: T;
  labelMustDeclare?: T;
  usualStandardization?:
    | T
    | {
        marker?: T;
        percent?: T;
        note?: T;
        id?: T;
      };
  labelAvoid?: T;
  referenceDose?:
    | T
    | {
        amount?: T;
        unit?: T;
        basis?: T;
        frequency?: T;
        refersTo?: T;
      };
  otherDoseReferences?:
    | T
    | {
        label?: T;
        amount?: T;
        unit?: T;
        source?: T;
        note?: T;
        id?: T;
      };
  block?: T;
  mealRelation?: T;
  mealNote?: T;
  usageInstructions?: T;
  introductionTags?: T;
  introductionNote?: T;
  rhythm?: T;
  rhythmOverride?:
    | T
    | {
        useWeeks?: T;
        pauseWeeks?: T;
        reviewEveryWeeks?: T;
        justification?: T;
      };
  selectiveUse?: T;
  selectiveCircumstances?: T;
  observations?:
    | T
    | {
        text?: T;
        answerType?: T;
        id?: T;
      };
  decisionCriteria?:
    | T
    | {
        situation?: T;
        decision?: T;
        id?: T;
      };
  tolerability?: T;
  adverseEffectsSummary?: T;
  adverseEffects?:
    | T
    | {
        effect?: T;
        frequency?: T;
        intensity?: T;
        id?: T;
      };
  alertSummary?:
    | T
    | {
        status?: T;
        text?: T;
      };
  precautions?:
    | T
    | {
        situation?: T;
        severity?: T;
        evidence?: T;
        visibleToCustomer?: T;
        action?: T;
        id?: T;
      };
  interactionSummary?:
    | T
    | {
        status?: T;
        text?: T;
      };
  interactions?:
    | T
    | {
        with?: T;
        kind?: T;
        severity?: T;
        evidence?: T;
        visibleToCustomer?: T;
        action?: T;
        id?: T;
      };
  pauseSignals?:
    | T
    | {
        text?: T;
        id?: T;
      };
  urgentSignals?:
    | T
    | {
        text?: T;
        id?: T;
      };
  evidenceSummary?: T;
  claims?:
    | T
    | {
        claim?: T;
        classification?: T;
        population?: T;
        preparationAndDose?: T;
        result?: T;
        sources?: T;
        id?: T;
      };
  moreWhatIs?: T;
  moreWhyUseful?: T;
  moreHowToUse?: T;
  moreCautions?: T;
  sources?: T;
  author?: T;
  reviewer?: T;
  approvedAt?: T;
  internalNotes?: T;
  editorialStatus?: T;
  poolStatus?: T;
  translationStatus?: T;
  regulatoryStatusCH?: T;
  regulatoryNote?: T;
  isFictional?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domains_select".
 */
export interface DomainsSelect<T extends boolean = true> {
  code?: T;
  clientName?: T;
  technicalName?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rhythms_select".
 */
export interface RhythmsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  description?: T;
  continuous?: T;
  useWeeks?: T;
  pauseWeeks?: T;
  reviewEveryWeeks?: T;
  pauseIsMinimum?: T;
  allowsSelectiveUse?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocks_select".
 */
export interface BlocksSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  description?: T;
  defaultTime?: T;
  mealRelation?: T;
  order?: T;
  provisional?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  authors?: T;
  year?: T;
  publication?: T;
  url?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  brand?: T;
  manufacturer?: T;
  form?: T;
  servingUnit?: T;
  unitsPerContainer?: T;
  shortDescription?: T;
  gtin?: T;
  currentFormulation?: T;
  labelImages?: T;
  sku?: T;
  price?: T;
  vatRate?: T;
  supplier?: T;
  weightGrams?: T;
  origin?:
    | T
    | {
        countryOfManufacture?: T;
        packagingPlace?: T;
        responsibleCompany?: T;
        ingredientOrigin?: T;
        evidence?: T;
      };
  storage?:
    | T
    | {
        conditions?: T;
        coldChainRequired?: T;
      };
  kind?: T;
  saleStatus?: T;
  isFictional?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formulations_select".
 */
export interface FormulationsSelect<T extends boolean = true> {
  product?: T;
  label?: T;
  version?: T;
  validFrom?: T;
  composition?:
    | T
    | {
        ingredient?: T;
        amount?: T;
        unit?: T;
        basis?: T;
        chemicalForm?: T;
        extractDetails?: T;
        id?: T;
      };
  labelInfo?:
    | T
    | {
        directions?: T;
        dailyUnitsMin?: T;
        dailyUnitsMax?: T;
        warnings?: T;
      };
  excipients?: T;
  allergens?: T;
  verificationStatus?: T;
  source?: T;
  sourceDate?: T;
  verifiedBy?: T;
  verifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers_select".
 */
export interface SuppliersSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  country?: T;
  website?: T;
  contact?:
    | T
    | {
        person?: T;
        email?: T;
        phone?: T;
      };
  terms?:
    | T
    | {
        summary?: T;
        minimumOrder?: T;
        paymentTerms?: T;
        inboundShipping?: T;
        resaleRights?: T;
        documents?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-submissions_select".
 */
export interface ProductSubmissionsSelect<T extends boolean = true> {
  customer?: T;
  productName?: T;
  manufacturer?: T;
  declaredIngredients?:
    | T
    | {
        ingredient?: T;
        amountText?: T;
        id?: T;
      };
  otherIngredients?: T;
  photos?: T;
  status?: T;
  resultProduct?: T;
  reviewNote?: T;
  verifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lots_select".
 */
export interface LotsSelect<T extends boolean = true> {
  product?: T;
  lotNumber?: T;
  expiryDate?: T;
  formulation?: T;
  supplier?: T;
  receivedOn?: T;
  quantityReceived?: T;
  supplierDocument?: T;
  storageLocation?: T;
  status?: T;
  statusNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements_select".
 */
export interface StockMovementsSelect<T extends boolean = true> {
  lot?: T;
  product?: T;
  kind?: T;
  bucket?: T;
  quantity?: T;
  order?: T;
  reason?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?: T;
  email?: T;
  language?: T;
  lines?:
    | T
    | {
        product?: T;
        formulation?: T;
        productName?: T;
        quantity?: T;
        unitPriceCents?: T;
        vatRate?: T;
        lots?:
          | T
          | {
              lot?: T;
              quantity?: T;
              id?: T;
            };
        id?: T;
      };
  totals?:
    | T
    | {
        subtotalCents?: T;
        shippingCents?: T;
        vatCents?: T;
        totalCents?: T;
      };
  shippingAddress?:
    | T
    | {
        name?: T;
        street?: T;
        addressLine2?: T;
        postalCode?: T;
        city?: T;
        country?: T;
      };
  shippingMethod?:
    | T
    | {
        code?: T;
        label?: T;
        priceCents?: T;
      };
  payment?:
    | T
    | {
        provider?: T;
        status?: T;
        reference?: T;
        paidAt?: T;
      };
  shipment?:
    | T
    | {
        trackingNumber?: T;
        depositedOn?: T;
        weightGrams?: T;
        deliveredOn?: T;
      };
  returns?:
    | T
    | {
        product?: T;
        lot?: T;
        quantity?: T;
        reason?: T;
        refundCents?: T;
        processed?: T;
        id?: T;
      };
  cancellationReason?: T;
  incidents?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-events_select".
 */
export interface PaymentEventsSelect<T extends boolean = true> {
  provider?: T;
  eventId?: T;
  type?: T;
  order?: T;
  amountCents?: T;
  outcome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  alias?: T;
  language?: T;
  adultConfirmed?: T;
  timezone?: T;
  isFictional?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consents_select".
 */
export interface ConsentsSelect<T extends boolean = true> {
  customer?: T;
  kind?: T;
  version?: T;
  grantedAt?: T;
  revokedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-products_select".
 */
export interface CustomerProductsSelect<T extends boolean = true> {
  customer?: T;
  product?: T;
  formulation?: T;
  status?: T;
  source?: T;
  order?: T;
  submission?: T;
  confirmedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  customer?: T;
  professionalReview?:
    | T
    | {
        status?: T;
        reviewer?: T;
        reviewedAt?: T;
        note?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plan-items_select".
 */
export interface PlanItemsSelect<T extends boolean = true> {
  customer?: T;
  plan?: T;
  customerProduct?: T;
  product?: T;
  formulation?: T;
  intakes?:
    | T
    | {
        block?: T;
        time?: T;
        servings?: T;
        id?: T;
      };
  note?: T;
  scheduleType?: T;
  weekdays?: T;
  selectiveCircumstances?: T;
  startDate?: T;
  rhythm?: T;
  reviewOn?: T;
  continuous?: T;
  useWeeks?: T;
  pauseWeeks?: T;
  reviewEveryWeeks?: T;
  pauseIsMinimum?: T;
  reviewQuestion?: T;
  observations?:
    | T
    | {
        text?: T;
        answerType?: T;
        id?: T;
      };
  status?: T;
  pauses?:
    | T
    | {
        from?: T;
        to?: T;
        reason?: T;
        id?: T;
      };
  endedOn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intake-logs_select".
 */
export interface IntakeLogsSelect<T extends boolean = true> {
  planItem?: T;
  customer?: T;
  date?: T;
  intakeIndex?: T;
  status?: T;
  servings?: T;
  note?: T;
  loggedAt?: T;
  correctedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  planItem?: T;
  customer?: T;
  dueDate?: T;
  kind?: T;
  status?: T;
  reviewQuestion?: T;
  answer?:
    | T
    | {
        questionAnswer?: T;
        observations?:
          | T
          | {
              text?: T;
              answerType?: T;
              value?: T;
              id?: T;
            };
        tolerability?: T;
        adherence?: T;
        perceivedChange?: T;
        answeredAt?: T;
      };
  outcome?: T;
  closedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "symptom-reports_select".
 */
export interface SymptomReportsSelect<T extends boolean = true> {
  customer?: T;
  planItem?: T;
  kind?: T;
  severity?: T;
  description?: T;
  reportedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  professionalTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  targetCollection?: T;
  targetId?: T;
  operation?: T;
  changedFields?: T;
  reason?: T;
  actorCollection?: T;
  actorId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "private-files_select".
 */
export interface PrivateFilesSelect<T extends boolean = true> {
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-settings".
 */
export interface ShopSetting {
  id: number;
  /**
   * Se cobra el transporte de forma transparente; sin umbral gratuito hasta calcularlo (Libro 1 v2.0, cap. 11).
   */
  shippingOptions?:
    | {
        code: string;
        label: string;
        price: number;
        maxWeightGrams?: number | null;
        deliveryNote?: string | null;
        id?: string | null;
      }[]
    | null;
  minShelfLifeDays: number;
  preparationNote?: string | null;
  /**
   * Vacío = el del primer artículo. Confirmar con asesoría fiscal.
   */
  shippingVatRate?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-settings_select".
 */
export interface ShopSettingsSelect<T extends boolean = true> {
  shippingOptions?:
    | T
    | {
        code?: T;
        label?: T;
        price?: T;
        maxWeightGrams?: T;
        deliveryNote?: T;
        id?: T;
      };
  minShelfLifeDays?: T;
  preparationNote?: T;
  shippingVatRate?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}