/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    ingredients: Ingredient;
    domains: Domain;
    rhythms: Rhythm;
    blocks: Block;
    sources: Source;
    products: Product;
    formulations: Formulation;
    chains: Chain;
    stores: Store;
    assortment: Assortment;
    users: User;
    customers: Customer;
    'customer-links': CustomerLink;
    invitations: Invitation;
    consents: Consent;
    plans: Plan;
    'plan-items': PlanItem;
    'intake-logs': IntakeLog;
    reviews: Review;
    'symptom-reports': SymptomReport;
    'audit-log': AuditLog;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    ingredients: IngredientsSelect<false> | IngredientsSelect<true>;
    domains: DomainsSelect<false> | DomainsSelect<true>;
    rhythms: RhythmsSelect<false> | RhythmsSelect<true>;
    blocks: BlocksSelect<false> | BlocksSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    formulations: FormulationsSelect<false> | FormulationsSelect<true>;
    chains: ChainsSelect<false> | ChainsSelect<true>;
    stores: StoresSelect<false> | StoresSelect<true>;
    assortment: AssortmentSelect<false> | AssortmentSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'customer-links': CustomerLinksSelect<false> | CustomerLinksSelect<true>;
    invitations: InvitationsSelect<false> | InvitationsSelect<true>;
    consents: ConsentsSelect<false> | ConsentsSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    'plan-items': PlanItemsSelect<false> | PlanItemsSelect<true>;
    'intake-logs': IntakeLogsSelect<false> | IntakeLogsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'symptom-reports': SymptomReportsSelect<false> | SymptomReportsSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'de-CH') | ('es' | 'de-CH')[];
  globals: {};
  globalsSelect: {};
  locale: 'es' | 'de-CH';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients".
 */
export interface Ingredient {
  id: number;
  name: string;
  /**
   * Minúsculas y guiones, p. ej. «rhodiola». No cambia entre idiomas.
   */
  slug: string;
  scientificName?: string | null;
  /**
   * Solo equipo editorial · búsqueda: sinónimos, nombres de etiqueta y de otros idiomas.
   */
  otherNames?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  category: 'vitamin' | 'mineral' | 'amino-acid' | 'fatty-acid' | 'plant-extract' | 'fungus' | 'other';
  /**
   * Solo para familias: omega-3 → EPA, DHA; complejo B → cada vitamina.
   */
  components?: (number | Ingredient)[] | null;
  /**
   * Lo ve el cliente · máx. 160 caracteres.
   */
  summary?: string | null;
  /**
   * Lo ve el cliente · máx. 300 caracteres.
   */
  whatIsShort?: string | null;
  primaryDomain?: (number | null) | Domain;
  /**
   * Solo con función distinta, observable y con respaldo humano.
   */
  secondaryDomain?: (number | null) | Domain;
  /**
   * Lo ve el personal de la droguería
   */
  domainJustification?: string | null;
  /**
   * Lo ve el personal de la droguería · máx. 400 caracteres.
   */
  mechanisms?: string | null;
  /**
   * Lo ve el personal de la droguería · nombre del campo provisional («Función de regreso MAT»).
   */
  goalTechnical?: string | null;
  /**
   * Lo ve el cliente · qué cambio concreto tendría sentido observar.
   */
  goalEveryday?: string | null;
  /**
   * Lo ve el cliente · una sola pregunta.
   */
  reviewQuestion?: string | null;
  /**
   * Lo ve el personal de la droguería
   */
  preferredForm?: string | null;
  labelMustDeclare?:
    | (
        | 'species'
        | 'part'
        | 'extract-type'
        | 'der'
        | 'solvent'
        | 'standardization'
        | 'chemical-form'
        | 'elemental-amount'
        | 'amount-per-dose'
        | 'manufacturer'
      )[]
    | null;
  usualStandardization?:
    | {
        marker: string;
        percent?: number | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  labelAvoid?: string | null;
  /**
   * Lo ve el personal de la droguería · información de contexto; no es un límite de seguridad (Libro 2, n.º 19).
   */
  referenceDose?: {
    amount?: number | null;
    unit?: ('mg' | 'ug' | 'g' | 'IU' | 'ml' | 'CFU') | null;
    basis?: ('extract' | 'elemental' | 'compound' | 'active' | 'blend') | null;
    frequency?: ('per-day' | 'per-use' | 'per-week') | null;
    /**
     * p. ej. «de extracto de raíz y rizoma»
     */
    refersTo?: string | null;
  };
  otherDoseReferences?:
    | {
        label: string;
        amount?: number | null;
        unit?: ('mg' | 'ug' | 'g' | 'IU' | 'ml' | 'CFU') | null;
        source?: (number | null) | Source;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  block?: (number | null) | Block;
  mealRelation?: ('fasting' | 'with-food' | 'any') | null;
  mealNote?: string | null;
  /**
   * Lo ve el cliente · se muestra junto a cada toma.
   */
  usageInstructions?: string | null;
  /**
   * p. ej. «activadora». Regla pendiente de confirmar (pendiente n.º 4).
   */
  introductionTags?: string[] | null;
  introductionNote?: string | null;
  rhythm?: (number | null) | Rhythm;
  /**
   * Dejar vacío para usar las de la plantilla. Si se cambian, justificar.
   */
  rhythmOverride?: {
    useWeeks?: number | null;
    pauseWeeks?: number | null;
    reviewEveryWeeks?: number | null;
    justification?: string | null;
  };
  selectiveUse?: boolean | null;
  selectiveCircumstances?: string | null;
  /**
   * Lo ve el cliente · 2–3 situaciones concretas. Se convierten en preguntas de la revisión.
   */
  observations?:
    | {
        text: string;
        answerType?: ('yes-no' | 'scale' | 'text') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Lo ve el personal de la droguería · orientan al profesional. El sistema no decide.
   */
  decisionCriteria?:
    | {
        situation: string;
        decision?: ('continue' | 'adjust' | 'new-cycle' | 'simplify' | 'pause' | 'withdraw' | 'refer') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Lo ve el cliente
   */
  tolerability?: string | null;
  /**
   * Lo ve el cliente · p. ej. «de frecuencia poco definida, generalmente leves y transitorios».
   */
  adverseEffectsSummary?: string | null;
  adverseEffects?:
    | {
        effect: string;
        frequency?: ('unknown' | 'rare' | 'uncommon' | 'common') | null;
        intensity?: ('mild' | 'moderate' | 'severe' | 'variable') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * «No» nunca se muestra como «sin riesgo». El detalle va en la lista correspondiente.
   */
  alertSummary: {
    status: 'yes' | 'no' | 'not-evaluated' | 'insufficient';
    text?: string | null;
  };
  precautions?:
    | {
        situation: string;
        severity?: ('low' | 'moderate' | 'high') | null;
        evidence?:
          | ('theoretical' | 'preclinical' | 'case-reports' | 'human-limited' | 'human-consistent' | 'established')
          | null;
        visibleToCustomer?: boolean | null;
        action?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * «No» nunca se muestra como «sin riesgo». El detalle va en la lista correspondiente.
   */
  interactionSummary: {
    status: 'yes' | 'no' | 'not-evaluated' | 'insufficient';
    text?: string | null;
  };
  interactions?:
    | {
        with: string;
        kind?: ('medication' | 'drug-class' | 'supplement' | 'food' | 'other') | null;
        severity?: ('low' | 'moderate' | 'high') | null;
        evidence?:
          | ('theoretical' | 'preclinical' | 'case-reports' | 'human-limited' | 'human-consistent' | 'established')
          | null;
        visibleToCustomer?: boolean | null;
        action?: string | null;
        id?: string | null;
      }[]
    | null;
  pauseSignals?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  urgentSignals?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lo ve el cliente en «Saber más»
   */
  evidenceSummary?: string | null;
  claims?:
    | {
        claim: string;
        classification: 'established' | 'possible' | 'exploratory' | 'traditional-use';
        population?: string | null;
        preparationAndDose?: string | null;
        result?: string | null;
        sources?: (number | Source)[] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Lo ve el cliente en «Saber más» · punto 2
   */
  moreWhatIs?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Lo ve el personal de la droguería · punto 3, sin el marco del aislamiento
   */
  moreWhyUseful?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Lo ve el personal de la droguería · punto 4
   */
  moreHowToUse?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * C+ y P · punto 5
   */
  moreCautions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sources?: (number | Source)[] | null;
  author?: (number | null) | User;
  reviewer?: (number | null) | User;
  approvedAt?: string | null;
  internalNotes?: string | null;
  /**
   * Solo las fichas aprobadas se publican. Aprobar requiere rol de revisión.
   */
  editorialStatus: 'draft' | 'in-review' | 'approved' | 'historical' | 'retired';
  /**
   * Un idioma no aprobado no se muestra al cliente (Libro 2, n.º 36).
   */
  translationStatus?: ('not-started' | 'draft' | 'reviewed' | 'approved') | null;
  regulatoryStatusCH: 'pending' | 'checked' | 'not-suitable';
  regulatoryNote?: string | null;
  isFictional?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domains".
 */
export interface Domain {
  id: number;
  /**
   * DF-1 … DF-7. No cambia aunque cambien los nombres.
   */
  code: string;
  clientName: string;
  technicalName: string;
  description?: string | null;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  title: string;
  kind: 'study' | 'review' | 'monograph' | 'regulatory' | 'internal' | 'other';
  authors?: string | null;
  year?: number | null;
  publication?: string | null;
  url?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocks".
 */
export interface Block {
  id: number;
  code: string;
  name: string;
  description?: string | null;
  defaultTime: string;
  mealRelation?: ('fasting' | 'with-food' | 'any') | null;
  order: number;
  provisional?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rhythms".
 */
export interface Rhythm {
  id: number;
  code: string;
  name: string;
  description?: string | null;
  continuous?: boolean | null;
  useWeeks?: number | null;
  pauseWeeks?: number | null;
  reviewEveryWeeks?: number | null;
  /**
   * Cosecha: «al menos doce semanas de pausa».
   */
  pauseIsMinimum?: boolean | null;
  /**
   * Cultivo puede incluir uso ante circunstancias definidas.
   */
  allowsSelectiveUse?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'newtons-admin' | 'editor' | 'reviewer' | 'chain-admin' | 'staff';
  chain?: (number | null) | Chain;
  /**
   * Vacío = todos los de la cadena.
   */
  stores?: (number | Store)[] | null;
  permissions?: ('invite' | 'prepare-plans' | 'confirm-plans' | 'view-shared-data')[] | null;
  professionalTitle?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chains".
 */
export interface Chain {
  id: number;
  name: string;
  slug: string;
  /**
   * Libro 2, n.º 34: logo, colores, nombre, contacto y bienvenida. Nada fijo en el código.
   */
  branding: {
    displayName: string;
    logo?: (number | null) | Media;
    primaryColor?: string | null;
    accentColor?: string | null;
    welcomeMessage?: string | null;
    coBranding?: 'shared' | null;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
  };
  isFictional?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stores".
 */
export interface Store {
  id: number;
  chain: number | Chain;
  name: string;
  street?: string | null;
  postalCode?: string | null;
  city?: string | null;
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  brand?: string | null;
  manufacturer?: string | null;
  form: 'capsule' | 'softgel' | 'tablet' | 'powder' | 'liquid' | 'gummy' | 'other';
  /**
   * p. ej. «cápsula», «medida de 5 g»
   */
  servingUnit: string;
  unitsPerContainer?: number | null;
  /**
   * Identificador, no prueba de composición (Libro 2, n.º 11).
   */
  gtin?: string[] | null;
  /**
   * Se rellena al verificar una formulación.
   */
  currentFormulation?: (number | null) | Formulation;
  labelImages?: (number | Media)[] | null;
  status: 'active' | 'discontinued';
  isFictional?: boolean | null;
  /**
   * Producto comprado fuera de la cadena, pendiente de verificación (Libro 2, n.º 12).
   */
  submittedByCustomer?: (number | null) | Customer;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formulations".
 */
export interface Formulation {
  id: number;
  product: number | Product;
  label?: string | null;
  version?: number | null;
  validFrom?: string | null;
  composition?:
    | {
        ingredient: number | Ingredient;
        /**
         * Vacío si la etiqueta no la declara.
         */
        amount?: number | null;
        unit?: ('mg' | 'ug' | 'g' | 'IU' | 'ml' | 'CFU') | null;
        basis: 'extract' | 'elemental' | 'compound' | 'active' | 'blend';
        /**
         * p. ej. «citrato de magnesio», «colecalciferol»
         */
        chemicalForm?: string | null;
        extractDetails?: string | null;
        id?: string | null;
      }[]
    | null;
  excipients?: string | null;
  allergens?: string | null;
  verificationStatus: 'pending' | 'verified' | 'rejected' | 'superseded';
  /**
   * Etiqueta, ficha del fabricante, archivo de la droguería…
   */
  source?: string | null;
  sourceDate?: string | null;
  verifiedBy?: (number | null) | User;
  verifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  alias: string;
  language: 'es' | 'de-CH';
  adultConfirmed: boolean;
  timezone?: string | null;
  /**
   * Se mantiene automáticamente desde las vinculaciones activas.
   */
  linkedChains?: (number | Chain)[] | null;
  isFictional?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assortment".
 */
export interface Assortment {
  id: number;
  chain: number | Chain;
  product: number | Product;
  /**
   * Vacío = toda la cadena.
   */
  stores?: (number | Store)[] | null;
  internalCode?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-links".
 */
export interface CustomerLink {
  id: number;
  customer: number | Customer;
  chain: number | Chain;
  store: number | Store;
  status: 'active' | 'revoked' | 'ended';
  sharing?: ('plan' | 'intake-logs' | 'reviews' | 'symptom-reports')[] | null;
  identityVerified?: boolean | null;
  invitedBy?: (number | null) | User;
  endedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations".
 */
export interface Invitation {
  id: number;
  email: string;
  chain: number | Chain;
  store: number | Store;
  status: 'pending' | 'accepted' | 'revoked';
  token?: string | null;
  expiresAt?: string | null;
  createdBy?: (number | null) | User;
  customer?: (number | null) | Customer;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consents".
 */
export interface Consent {
  id: number;
  customer: number | Customer;
  kind: 'terms' | 'privacy' | 'share-with-chain';
  chain?: (number | null) | Chain;
  version: string;
  grantedAt?: string | null;
  revokedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  title: string;
  customer: number | Customer;
  chain: number | Chain;
  store?: (number | null) | Store;
  goal?: string | null;
  status: 'draft' | 'pending-confirmation' | 'active' | 'ended';
  preparedBy?: (number | null) | User;
  confirmedBy?: (number | null) | User;
  confirmedAt?: string | null;
  /**
   * Obligatorio al modificar un plan que no es borrador.
   */
  changeReason?: string | null;
  professionalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plan-items".
 */
export interface PlanItem {
  id: number;
  plan: number | Plan;
  customer?: (number | null) | Customer;
  chain?: (number | null) | Chain;
  store?: (number | null) | Store;
  product: number | Product;
  /**
   * Por defecto, la vigente al crear la línea. No cambia sola.
   */
  formulation?: (number | null) | Formulation;
  servingsPerIntake: number;
  block?: (number | null) | Block;
  /**
   * El cliente puede cambiarla; no altera la pauta.
   */
  reminderTime?: string | null;
  instructions?: string | null;
  scheduleType: 'daily' | 'weekdays' | 'selective';
  weekdays?: ('mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun')[] | null;
  selectiveCircumstances?: string | null;
  selectiveMaxPerDay?: number | null;
  selectiveMinIntervalHours?: number | null;
  rhythm?: (number | null) | Rhythm;
  /**
   * AAAA-MM-DD
   */
  startDate: string;
  continuous?: boolean | null;
  useWeeks?: number | null;
  pauseWeeks?: number | null;
  reviewEveryWeeks?: number | null;
  pauseIsMinimum?: boolean | null;
  status: 'active' | 'paused' | 'interrupted' | 'ended';
  /**
   * Libro 2, n.º 23: una pausa no alarga ni reinicia el ciclo.
   */
  pauses?:
    | {
        from: string;
        to?: string | null;
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  endedOn?: string | null;
  reviewQuestion?: string | null;
  observations?:
    | {
        text: string;
        answerType?: ('yes-no' | 'scale' | 'text') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Libro 2, n.º 20: se guardan como «pendiente de revisión»; no cambian la pauta aprobada.
   */
  declaredChanges?:
    | {
        description: string;
        declaredAt?: string | null;
        status?: ('pending' | 'reviewed') | null;
        id?: string | null;
      }[]
    | null;
  changeReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intake-logs".
 */
export interface IntakeLog {
  id: number;
  planItem: number | PlanItem;
  customer?: (number | null) | Customer;
  chain?: (number | null) | Chain;
  store?: (number | null) | Store;
  date: string;
  block?: (number | null) | Block;
  status: 'taken' | 'skipped' | 'postponed';
  servings?: number | null;
  note?: string | null;
  loggedAt?: string | null;
  correctedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  planItem: number | PlanItem;
  customer?: (number | null) | Customer;
  chain?: (number | null) | Chain;
  store?: (number | null) | Store;
  dueDate: string;
  kind: 'periodic' | 'end-of-use' | 'end-of-pause' | 'extra';
  status: 'pending' | 'answered' | 'closed';
  reviewQuestion?: string | null;
  answer?: {
    questionAnswer?: string | null;
    observations?:
      | {
          text?: string | null;
          answerType?: ('yes-no' | 'scale' | 'text') | null;
          value?: string | null;
          id?: string | null;
        }[]
      | null;
    tolerability?: ('good' | 'some' | 'poor') | null;
    adherence?: ('as-planned' | 'partial' | 'stopped') | null;
    perceivedChange?: string | null;
    answeredAt?: string | null;
  };
  outcome?: ('continue' | 'adjust' | 'new-cycle' | 'simplify' | 'pause' | 'withdraw' | 'refer') | null;
  decidedBy?: (number | null) | User;
  decidedAt?: string | null;
  professionalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "symptom-reports".
 */
export interface SymptomReport {
  id: number;
  planItem?: (number | null) | PlanItem;
  customer: number | Customer;
  chain: number | Chain;
  store?: (number | null) | Store;
  kind: 'question' | 'discomfort' | 'adherence' | 'stopped';
  severity?: ('mild' | 'moderate' | 'severe') | null;
  status: 'open' | 'seen';
  description: string;
  reportedAt?: string | null;
  seenBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  targetCollection: string;
  targetId: string;
  operation: 'create' | 'update' | 'delete';
  changedFields?: string[] | null;
  reason?: string | null;
  actorCollection?: string | null;
  actorId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'ingredients';
        value: number | Ingredient;
      } | null)
    | ({
        relationTo: 'domains';
        value: number | Domain;
      } | null)
    | ({
        relationTo: 'rhythms';
        value: number | Rhythm;
      } | null)
    | ({
        relationTo: 'blocks';
        value: number | Block;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'formulations';
        value: number | Formulation;
      } | null)
    | ({
        relationTo: 'chains';
        value: number | Chain;
      } | null)
    | ({
        relationTo: 'stores';
        value: number | Store;
      } | null)
    | ({
        relationTo: 'assortment';
        value: number | Assortment;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'customer-links';
        value: number | CustomerLink;
      } | null)
    | ({
        relationTo: 'invitations';
        value: number | Invitation;
      } | null)
    | ({
        relationTo: 'consents';
        value: number | Consent;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'plan-items';
        value: number | PlanItem;
      } | null)
    | ({
        relationTo: 'intake-logs';
        value: number | IntakeLog;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'symptom-reports';
        value: number | SymptomReport;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ingredients_select".
 */
export interface IngredientsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  scientificName?: T;
  otherNames?:
    | T
    | {
        value?: T;
        id?: T;
      };
  category?: T;
  components?: T;
  summary?: T;
  whatIsShort?: T;
  primaryDomain?: T;
  secondaryDomain?: T;
  domainJustification?: T;
  mechanisms?: T;
  goalTechnical?: T;
  goalEveryday?: T;
  reviewQuestion?: T;
  preferredForm?: T;
  labelMustDeclare?: T;
  usualStandardization?:
    | T
    | {
        marker?: T;
        percent?: T;
        note?: T;
        id?: T;
      };
  labelAvoid?: T;
  referenceDose?:
    | T
    | {
        amount?: T;
        unit?: T;
        basis?: T;
        frequency?: T;
        refersTo?: T;
      };
  otherDoseReferences?:
    | T
    | {
        label?: T;
        amount?: T;
        unit?: T;
        source?: T;
        note?: T;
        id?: T;
      };
  block?: T;
  mealRelation?: T;
  mealNote?: T;
  usageInstructions?: T;
  introductionTags?: T;
  introductionNote?: T;
  rhythm?: T;
  rhythmOverride?:
    | T
    | {
        useWeeks?: T;
        pauseWeeks?: T;
        reviewEveryWeeks?: T;
        justification?: T;
      };
  selectiveUse?: T;
  selectiveCircumstances?: T;
  observations?:
    | T
    | {
        text?: T;
        answerType?: T;
        id?: T;
      };
  decisionCriteria?:
    | T
    | {
        situation?: T;
        decision?: T;
        id?: T;
      };
  tolerability?: T;
  adverseEffectsSummary?: T;
  adverseEffects?:
    | T
    | {
        effect?: T;
        frequency?: T;
        intensity?: T;
        id?: T;
      };
  alertSummary?:
    | T
    | {
        status?: T;
        text?: T;
      };
  precautions?:
    | T
    | {
        situation?: T;
        severity?: T;
        evidence?: T;
        visibleToCustomer?: T;
        action?: T;
        id?: T;
      };
  interactionSummary?:
    | T
    | {
        status?: T;
        text?: T;
      };
  interactions?:
    | T
    | {
        with?: T;
        kind?: T;
        severity?: T;
        evidence?: T;
        visibleToCustomer?: T;
        action?: T;
        id?: T;
      };
  pauseSignals?:
    | T
    | {
        text?: T;
        id?: T;
      };
  urgentSignals?:
    | T
    | {
        text?: T;
        id?: T;
      };
  evidenceSummary?: T;
  claims?:
    | T
    | {
        claim?: T;
        classification?: T;
        population?: T;
        preparationAndDose?: T;
        result?: T;
        sources?: T;
        id?: T;
      };
  moreWhatIs?: T;
  moreWhyUseful?: T;
  moreHowToUse?: T;
  moreCautions?: T;
  sources?: T;
  author?: T;
  reviewer?: T;
  approvedAt?: T;
  internalNotes?: T;
  editorialStatus?: T;
  translationStatus?: T;
  regulatoryStatusCH?: T;
  regulatoryNote?: T;
  isFictional?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "domains_select".
 */
export interface DomainsSelect<T extends boolean = true> {
  code?: T;
  clientName?: T;
  technicalName?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rhythms_select".
 */
export interface RhythmsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  description?: T;
  continuous?: T;
  useWeeks?: T;
  pauseWeeks?: T;
  reviewEveryWeeks?: T;
  pauseIsMinimum?: T;
  allowsSelectiveUse?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocks_select".
 */
export interface BlocksSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  description?: T;
  defaultTime?: T;
  mealRelation?: T;
  order?: T;
  provisional?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  authors?: T;
  year?: T;
  publication?: T;
  url?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  brand?: T;
  manufacturer?: T;
  form?: T;
  servingUnit?: T;
  unitsPerContainer?: T;
  gtin?: T;
  currentFormulation?: T;
  labelImages?: T;
  status?: T;
  isFictional?: T;
  submittedByCustomer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formulations_select".
 */
export interface FormulationsSelect<T extends boolean = true> {
  product?: T;
  label?: T;
  version?: T;
  validFrom?: T;
  composition?:
    | T
    | {
        ingredient?: T;
        amount?: T;
        unit?: T;
        basis?: T;
        chemicalForm?: T;
        extractDetails?: T;
        id?: T;
      };
  excipients?: T;
  allergens?: T;
  verificationStatus?: T;
  source?: T;
  sourceDate?: T;
  verifiedBy?: T;
  verifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chains_select".
 */
export interface ChainsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  branding?:
    | T
    | {
        displayName?: T;
        logo?: T;
        primaryColor?: T;
        accentColor?: T;
        welcomeMessage?: T;
        coBranding?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
      };
  isFictional?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stores_select".
 */
export interface StoresSelect<T extends boolean = true> {
  chain?: T;
  name?: T;
  street?: T;
  postalCode?: T;
  city?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assortment_select".
 */
export interface AssortmentSelect<T extends boolean = true> {
  chain?: T;
  product?: T;
  stores?: T;
  internalCode?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  chain?: T;
  stores?: T;
  permissions?: T;
  professionalTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  alias?: T;
  language?: T;
  adultConfirmed?: T;
  timezone?: T;
  linkedChains?: T;
  isFictional?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-links_select".
 */
export interface CustomerLinksSelect<T extends boolean = true> {
  customer?: T;
  chain?: T;
  store?: T;
  status?: T;
  sharing?: T;
  identityVerified?: T;
  invitedBy?: T;
  endedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations_select".
 */
export interface InvitationsSelect<T extends boolean = true> {
  email?: T;
  chain?: T;
  store?: T;
  status?: T;
  token?: T;
  expiresAt?: T;
  createdBy?: T;
  customer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consents_select".
 */
export interface ConsentsSelect<T extends boolean = true> {
  customer?: T;
  kind?: T;
  chain?: T;
  version?: T;
  grantedAt?: T;
  revokedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  title?: T;
  customer?: T;
  chain?: T;
  store?: T;
  goal?: T;
  status?: T;
  preparedBy?: T;
  confirmedBy?: T;
  confirmedAt?: T;
  changeReason?: T;
  professionalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plan-items_select".
 */
export interface PlanItemsSelect<T extends boolean = true> {
  plan?: T;
  customer?: T;
  chain?: T;
  store?: T;
  product?: T;
  formulation?: T;
  servingsPerIntake?: T;
  block?: T;
  reminderTime?: T;
  instructions?: T;
  scheduleType?: T;
  weekdays?: T;
  selectiveCircumstances?: T;
  selectiveMaxPerDay?: T;
  selectiveMinIntervalHours?: T;
  rhythm?: T;
  startDate?: T;
  continuous?: T;
  useWeeks?: T;
  pauseWeeks?: T;
  reviewEveryWeeks?: T;
  pauseIsMinimum?: T;
  status?: T;
  pauses?:
    | T
    | {
        from?: T;
        to?: T;
        reason?: T;
        id?: T;
      };
  endedOn?: T;
  reviewQuestion?: T;
  observations?:
    | T
    | {
        text?: T;
        answerType?: T;
        id?: T;
      };
  declaredChanges?:
    | T
    | {
        description?: T;
        declaredAt?: T;
        status?: T;
        id?: T;
      };
  changeReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intake-logs_select".
 */
export interface IntakeLogsSelect<T extends boolean = true> {
  planItem?: T;
  customer?: T;
  chain?: T;
  store?: T;
  date?: T;
  block?: T;
  status?: T;
  servings?: T;
  note?: T;
  loggedAt?: T;
  correctedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  planItem?: T;
  customer?: T;
  chain?: T;
  store?: T;
  dueDate?: T;
  kind?: T;
  status?: T;
  reviewQuestion?: T;
  answer?:
    | T
    | {
        questionAnswer?: T;
        observations?:
          | T
          | {
              text?: T;
              answerType?: T;
              value?: T;
              id?: T;
            };
        tolerability?: T;
        adherence?: T;
        perceivedChange?: T;
        answeredAt?: T;
      };
  outcome?: T;
  decidedBy?: T;
  decidedAt?: T;
  professionalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "symptom-reports_select".
 */
export interface SymptomReportsSelect<T extends boolean = true> {
  planItem?: T;
  customer?: T;
  chain?: T;
  store?: T;
  kind?: T;
  severity?: T;
  status?: T;
  description?: T;
  reportedAt?: T;
  seenBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  targetCollection?: T;
  targetId?: T;
  operation?: T;
  changedFields?: T;
  reason?: T;
  actorCollection?: T;
  actorId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}